services:
  client:
    container_name: client_container
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    command: [ "npm", "run", "dev" ]
  server:
    container_name: server_container
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: [ "npm", "run", "dev" ]
  db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrepassword
      POSTGRES_DB: puttdle_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  pgdata:
