name: Docker Build and Compose Client

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-compose:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build client Docker image
      run: |
        docker build -t client:latest -f ./client/Dockerfile ./client

    - name: Run docker-compose
      run: |
        docker-compose up -d
        docker-compose ps