name: Server Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Server Tests
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 20.0
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Move into server directory
        run: |
          cd server/

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test