name: Lint test server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server/src
    steps:
      - name: Use Node.js 20.0
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint