name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: "development"
      DB_HOST: "db"
      DB_USER: "postgres"
      DB_PASS: "postgrepassword"
      DB_NAME: "puttdle_dev"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          cd server
          touch .env
          echo NODE_ENV="development" >> .env
          echo DB_HOST="db" >> .env
          echo DB_USER="postgres" >> .env
          echo DB_PASS="postgrepassword" >> .env
          echo DB_NAME="puttdle_dev" >> .env
          cat .env

      - name: Docker compose up
        run: docker-compose up -d --build

      - name: Check running containers
        run: docker ps -a

      - name: Run test suite
        run: docker exec server_container npm run test
