name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Dockerfile Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Move into server directory
        run: |
          cd server/

      - name: Build the Docker image
        run: docker build . --tag server:$(date +%s)