name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    env:
      NODE_ENV: "development"
      DB_HOST: "db"
      DB_USER: "postgres"
      DB_PASS: "postgrepassword"
      DB_NAME: "puttdle_dev"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker compose up
        run: docker-compose up
