name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: hoverkraft-tech/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"
        env:
          NODE_ENV: "development"
          DB_HOST: "db"
          DB_USER: "postgres"
          DB_PASS: "postgrepassword"
          DB_NAME: "puttdle_dev"